### ISSUE TITLE
About model.py line 105

### ISSUE THREAD

**Issue by BangLiu** [pranz24/pytorch-soft-actor-critic#17]
In model line 105, isn't the third return value should be:

    torch.tanh(mean) * self.action_scale + self.action_bias

?

**Comment by pranz24** [comment]
Yes
Although @ku2482 will know better than me.

**Comment by toshikwa** [comment]
@BangLiu 
Yes, sorry for my easy mistake @pranz24 .

**Comment by pranz24** [comment]
Awesome
I'll fix it
