### ISSUE TITLE
Could you please explain the "# Enforcing Action Bound" comment?

### ISSUE THREAD

**Issue by Wen-Wen-Luffy** [pranz24/pytorch-soft-actor-critic#18]
In model.py line 102 and 103:

**# Enforcing Action Bound
log_prob -= torch.log(self.action_scale * (1 - y_t.pow(2)) + epsilon)**

refer to the original paper, I can not understand the aim of this line of code.

I try some code like GaussianPolicy.sample(), and sometimes get positive _log_prob_ in the end, and I'm still confused about this line. 

Could you please explain it? Thank you very much!

**Comment by pranz24** [comment]
It's just the change of variables formula to bound the action distribution to (-1, 1).

![Screenshot from 2019-09-25 13-02-50](https://user-images.githubusercontent.com/18737539/65579527-8cfca700-df95-11e9-95b2-26fa39014fda.png)

**Comment by Wen-Wen-Luffy** [comment]
Thank you very much! 
I'll read it deeply and close this comment

**Comment by sungsulim** [comment]
Oops there was a duplicate issue here.
In the paper, they do not have any multiplication of action_scale
Could you help me understand why self.action_scale is multiplied?

**Comment by Roythuly** [comment]
self.action_scale,  can I ask why needs this term?
