### ISSUE TITLE
puzzles about action scaling

### ISSUE THREAD

**Issue by wayunderfoot** [pranz24/pytorch-soft-actor-critic#20]
Hi,thanks for your pytorch implementation of SAC,it's really readable.
I have a question about action scaling when i read your code.
https://github.com/pranz24/pytorch-soft-actor-critic/blob/cc42a1f31c0a5764548641ccbffe1561ba00622a/model.py#L100
What is its function if action_scale equals 1.0 and action_bias equals 0.And why can that make a big improment upon performence?

**Comment by pranz24** [comment]
In practice, I don't think it ever made any difference in the performance. (at least on mujoco tasks).
Stability-wise, I think, the performance should be more stable. (intuition :neutral_face:)
You can go through this pull request to understand why we are doing action re-scaling: [Fix bugs of action re-scaling](https://github.com/pranz24/pytorch-soft-actor-critic/pull/15)

**Comment by wayunderfoot** [comment]
Thanks,i will check it out.
