### ISSUE TITLE
Why is the value function not used in this implementation?

### ISSUE THREAD

**Issue by Steven-Ho** [pranz24/pytorch-soft-actor-critic#22]
I noticed two Q-functions and one V-function were presented in the SAC algorithm in the original paper. And so it is in the author's implementation (see https://github.com/haarnoja/sac/blob/master/sac/algos/diayn.py).
Is there some consideration on computation costs or training stability?

**Comment by twni2016** [comment]
Same question here. Will not using it affect the performance?

**Comment by pranz24** [comment]
Yup,  the paper ([Soft Actor-Critic: Off-Policy Maximum Entropy Deep Reinforcement
Learning with a Stochastic Actor](https://arxiv.org/pdf/1801.01290.pdf)) does use a value function. (I made another branch for this paper - https://github.com/pranz24/pytorch-soft-actor-critic/tree/SAC_V).

 
I don't think there is much of a difference in terms of training stability, although I haven't tested this thoroughly. (Not the exact same question but the author does mention here that they didn't see any noticeable difference by removing the value function - https://github.com/rail-berkeley/softlearning/issues/30)

In terms of computational cost, adding a value function is an overhead.

**Comment by twni2016** [comment]
Thanks for the explanation!

**Comment by Steven-Ho** [comment]
@pranz24 thanks! I tried one run on Halfcheetah-v2 to see the difference (I add a value function and a target network, and canceled the target networks of Q function). It seems to take more episodes to learn. Maybe it's harder to learn one extra network.
![Screenshot from 2019-11-27 18-42-11](https://user-images.githubusercontent.com/4974362/69716799-c2647300-1145-11ea-9aa5-ff91f05b62f5.png)

Your idea is great!
