### ISSUE TITLE
Inconsistent seeding

### ISSUE THREAD

**Issue by mohakbhardwaj** [pranz24/pytorch-soft-actor-critic#32]
Hi,

I just wanted to point out that the code produces inconsistent results on multiple runs due to seeding issues. I have found two reasons for that, upon fixing which I am able to get consistent results for a fixed seed value.

1. The Python random package is used in ReplayMemory. However, the seed for it is not set in main.py
2. You would need set the seed for the action_space for the environment explicitly using `env.action_space.seed(args.seed)` as the `env.seed(seed)` function does not do that. This gives different action samples in the initial exploration phase of the algorithm. I am using Gym version 0.17.2

Hope this helps!

**Comment by pranz24** [comment]
Thank you! :raised_hands:

I wasn't aware of the 2nd point. I'll fix the issue within this week.

**Comment by pranz24** [comment]
I think I have fixed the problem.
Do let me know if there is something wrong here. [Fix inconsistent seeding & clean up code](https://github.com/pranz24/pytorch-soft-actor-critic/commit/1bd1158116edb02b09a8f8f361640eaeee84447e)

**Comment by pranz24** [comment]
[Fix inconsistent seeding & clean up](https://github.com/pranz24/pytorch-soft-actor-critic/commit/1bd1158116edb02b09a8f8f361640eaeee84447e)
