### ISSUE TITLE
[Question] Mask Batch

### ISSUE THREAD

**Issue by chenxi-yang** [pranz24/pytorch-soft-actor-critic#42]
Hi,

For this [line](https://github.com/pranz24/pytorch-soft-actor-critic/blob/master/sac.py#L66): why do you need the mask batch here? In the original SAC paper, the target q value is represented by `r+\gamma*Q(st+1, at+1)`. Does removing the mask batch here affect the performance?

Thanks

**Comment by signinme** [comment]
Q(st+1. at+1)=0 if st is the final state

**Comment by pranz24** [comment]
> Does removing the mask batch here affect the performance

It does if I remember correctly
