### ISSUE TITLE
Is this code SAC-V not a SAC?

### ISSUE THREAD

**Issue by night2570** [pranz24/pytorch-soft-actor-critic#43]
I thought this implementation was SAC rather than SAC-V.
however, it seems like the agent does not contian ValueNetowrk, while the model.py include the ValuenNetwork. 
I am wondering this code of SAC-V and the value network is trace of previous implementation.

**Comment by pranz24** [comment]
Yes. 
If you want you can send a pull request removing the ValueNetwork. (Doesn't really matter)
(Very Sorry for the late reply.)
